name 'serverascode-saio'
version '0.2.6'
dependency 'puppetlabs/vcsrepo'
dependency 'puppetlabs/stdlib'
summary "Deploy OpenStack Swift-all-in-one"
description 'Deploys OpenStack Swift with all services running on a single server for development and testing.'
project_page 'http://github.com/curtisgithub/puppet-saio'
author 'curtis@serverascode.com'
license 'GPL V3'
